PassionProject_N01329942/Models/Team.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;


namespace PassionProject_N01329942.Models
{
    public class Team
    {
        [Key,ScaffoldColumn(false)]
        public int TeamID { get; set; }

        [Required, StringLength(50), Display(Name ="Team Name")]
        public string TeamName { get; set; }

        [Required, StringLength(50), Display(Name = "Date Established")]
        public string EstablishDate { get; set; }

        // one team has many players one to many relationship
        public virtual ICollection<Player> PLayers { get; set; }

        // foreign key countryID
        public virtual Country country { get; set; }
    }
}

PassionProject_N01329942/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using PassionProject_N01329942.Models;
using PassionProject_N01329942.Models.ViewModels;
using System.Diagnostics;
using System.IO;

namespace PassionProject_N01329942.Controllers
{
    public class TeamController : Controller
    {
        private SoccerCMSContext db = new SoccerCMSContext();
        // GET: Team
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        /* List action controller to list the Teams table. Also,
        we will have one column of country name from Countries table
        */
        public ActionResult List()
        {
            
            IEnumerable<Team> teams = db.Teams.ToList();

            /* (Or we could use this way to display Team database content)
             * string query = "select * from Teams";
             * IEnumerable<Team> teams = db.Teams.SqlQuery(query); 
             */

            return View(teams);
        }

        // Add action controller to add a new team
        public ActionResult Add()
        {
            TeamEdit EditedTeam = new TeamEdit();
            EditedTeam.countries = db.Countries.ToList();
            return View(EditedTeam);
        }
        [HttpPost]
        public ActionResult Create(string TeamName_New, string EstablishDate_New, int CountryID_New)
        {
            string subquery = "insert into Teams (TeamName, EstablishDate, Country_CountryID) " +
                           "values (@name,@establishdate,@country)";

            SqlParameter[] myparams = new SqlParameter[3];
            myparams[0] = new SqlParameter("@name", TeamName_New);
            myparams[1] = new SqlParameter("@establishdate", EstablishDate_New);
            myparams[2] = new SqlParameter("@country", CountryID_New);

            db.Database.ExecuteSqlCommand(subquery, myparams);
            Debug.WriteLine(subquery);

            return RedirectToAction("List"); // after adding a team, it will redirect back to List View.
        }
        public ActionResult Edit(int? id)
        {
            TeamEdit EditedTeam = new TeamEdit();
            EditedTeam.countries = db.Countries.ToList();
            EditedTeam.team = db.Teams.Find(id);

            return View();
        }

        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Team team = db.Teams.Find(id);
            if (team == null)
            {
                return HttpNotFound();
            }
            return View(team);
        }

        /*
         * I had to add [HttpGet] since I have two actions with the same name,
         * it gave me an error of ambigious actions. Therefore, I added [HttpGet]
         * which i got this help from 
         * https://forums.asp.net/t/1714974.aspx?+foreach+var+item+in+Model+Object+reference+not+set+to+an+instance+of+an+object+
         */
        [HttpGet]
        public ActionResult Edit(int id)
        {

            TeamEdit EditedTeam = new TeamEdit();
            EditedTeam.countries = db.Countries.ToList();
            
            EditedTeam.team = db.Teams.Find(id);

            return View(EditedTeam);
        }

        [HttpPost]
        public ActionResult Edit(int id,string TeamName_Edit, string EstablishDate_Edit, int CountryID_Edit)
        {
            if ((id == null) || (db.Teams.Find(id) == null))
            {
                return HttpNotFound();
            }
            string subquery = "UPDATE teams SET TeamName = @teamname, EstablishDate = @establishdate," +
                              " country_CountryID =@country " +
                              " WHERE teamid = @id";
            SqlParameter[] myparams = new SqlParameter[4];
            myparams[0] = new SqlParameter("@teamname", TeamName_Edit);
            myparams[1] = new SqlParameter("@establishdate", EstablishDate_Edit);
            myparams[2] = new SqlParameter("@country", CountryID_Edit);
            myparams[3] = new SqlParameter("@id", id);

            db.Database.ExecuteSqlCommand(subquery, myparams);

            return RedirectToAction("List");
        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Team team = db.Teams.Find(id);
            if (team == null)
            {
                return HttpNotFound();
            }

            return View(team);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Team team = db.Teams.Find(id);
            db.Teams.Remove(team);
            db.SaveChanges();
            return RedirectToAction("Index"); // To go back to Country/Index 

        }
    }
}

PassionProject_N01329942/Views/Team/Add.cshtml
@model PassionProject_N01329942.Models.ViewModels.TeamEdit
@{
    ViewBag.Title = "Add";
}
<div class="title">
    <h2>Add a New Team</h2>
</div>


<form method="POST" action="/Team/Create" id="myform">
    <div class="row">
        <div class="label">
            <label>Team Name: </label>
        </div>
        <div class="right-side">
            <input type="text" id="TeamName_New" name="TeamName_New" required="required" />
        </div>
    </div>
    <div class="row">
        <div class="label">
            <label>Established Date: </label>
        </div>
        <div class="right-side">
            <input type="text" id="EstablishDate_New" name="EstablishDate_New" required="required" />
        </div>
    </div>
    <div class="row">
        <div class="label">
            <label>Country Name: </label>
        </div>
        <div class="right-side">
            <select id="CountryID_New" name="CountryID_New">
                @foreach (var country in Model.countries)
                {
                    <option value="@country.CountryID">@country.CountryName</option>
                }
            </select>
        </div>
    </div>
    <div class="row center">
        <input type="submit" value="ADD" id="submit" />
    </div>
</form>
<div class="center">
    <button class="buttonLink">@Html.ActionLink("Back to Teams list", "Index")</button>
</div>

PassionProject_N01329942/Views/Team/Delete.cshtml
@model PassionProject_N01329942.Models.Team
@{
    ViewBag.Title = "Delete";
}
<div class="title">
    <h2>Delete a Team</h2>

    <h2>Do you want to delete this team from the list ?</h2>

    <h4>@Html.DisplayFor(model => model.TeamName)</h4>

</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="center">
        <input type="submit" value="Delete" id="submit" />
    </div>
    <div class="center">
        <button class="buttonLink">@Html.ActionLink("Back to teams list", "List")</button>
    </div>
}

PassionProject_N01329942/Views/Team/Edit.cshtml
@model PassionProject_N01329942.Models.ViewModels.TeamEdit
@{
    ViewBag.Title = "Edit";
}

<div class="title">
    <h2>Edit</h2>


    <form method="POST" action="@Model.team.TeamID">
        <div class="row hidden">
            <div class="label">
                <label>Team Name:</label>
            </div>
            <div class="right-side">
                <input type="text" value="@Model.team.TeamName" id="TeamName_Edit" name="TeamName_Edit" />
            </div>
        </div>
        <div class="row">
            <div class="label">
                <label>Establish Date:</label>
            </div>
            <div class="right-side">
                <input type="text" value="@Model.team.EstablishDate" id="EstablishDate_Edit" name="EstablishDate_Edit" />
            </div>
        </div>
        <div class="row">
            <div class="label">
                <label>Country Name:</label>
            </div>
            <div class="right-side">
                <select id="CountryID_Edit" name="CountryID_Edit">
                    @foreach (var country in Model.countries)
                    {
                        <option value="@country.CountryID"
                            @if(country.CountryID == Model.team.country.CountryID)
                            {
                                var selected = "selected";
                                @selected;
                            }>
                            @country.CountryName
                        </option>
                    }
                </select>
            </div>
        </div>
        <div class="row">
            <input type="submit" value="Save" id="submit" />
        </div>
    </form>

</div>
<div class="center">
    <button class="buttonLink">@Html.ActionLink("Back to Teams list", "List")</button>
</div>
    

PassionProject_N01329942/Views/Team/List.cshtml
@model IEnumerable<PassionProject_N01329942.Models.Team>
<!-- We have used IEnumerable interface since we will have a
    rendering loop to iterate through Team database-->
@{
    ViewBag.Title = "Teams";
}
<div class="title">
    <h2>Teams</h2>

    <button class="buttonLink">@Html.ActionLink("Add a new Team", "Add", "Team")</button>
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TeamName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EstablishDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.country.CountryName)
        </th>
        <th>
            Features
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TeamName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EstablishDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.country.CountryName)
            </td>

            <td>
                @Html.ActionLink("Details", "details", new { id = item.TeamID }) |
                @Html.ActionLink("Edit", "Edit", new { id = item.TeamID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.TeamID })
            </td>
        </tr>
    }
</table>

PassionProject_N01329942/Views/Team/details.cshtml
@model  PassionProject_N01329942.Models.Team
@{
    ViewBag.Title = "details";
}
<div class="title">
    <h2>Team details</h2>

    <h2><strong>@Model.TeamName</strong></h2>

    <h3>Was Established in <strong>@Model.EstablishDate</strong></h3>

    <h3>Plays in <strong>@Model.country.CountryName</strong></h3>
    
    <div>
        <button class="buttonLink">@Html.ActionLink("Back to team List", "Index")</button>
    </div>
</div>