PassionProject_N01329942/Models/Player.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;

namespace PassionProject_N01329942.Models
{
    public class Player
    {
        //One team has many players
        //One country has many players
        [Key, ScaffoldColumn(false)]
        public int PlayerID { get; set; }

        // Player First Name Column
        [Required, StringLength(50), Display(Name = "Player First Name")]
        public string PlayerFName { get; set; }

        // Player Last Name Column
        [Required, StringLength(50), Display(Name = "Player Last Name")]
        public string PlayerLName { get; set; }

        // Player Age Column
        [Required, StringLength(50), Display(Name = "Player Age")]
        public string PlayerAge { get; set; }

        // Player nationality Column
        [StringLength(50), Display(Name = "Nationality")]
        public string PlayerNationality { get; set; }

        // Player Position Column
        [StringLength(50), Display(Name = "Player Position")]
        public string PlayerPosition { get; set; }

        // one team can have many players
        public virtual Team team { get; set; }
    }

}

PassionProject_N01329942/Controllers/PlayerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using PassionProject_N01329942.Models;
using PassionProject_N01329942.Models.ViewModels;
using System.Diagnostics;
using System.IO;

namespace PassionProject_N01329942.Controllers
{
    public class PlayerController : Controller
    {
        private SoccerCMSContext db = new SoccerCMSContext();
        // GET: Player
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }
        public ActionResult List()
        {
            /*
            string query = "select * from Players";
            IEnumerable<Player> players = db.Players.SqlQuery(query);
            */
            
             IEnumerable<Player> players = db.Players.ToList();
             

            return View(players);
        }
        public ActionResult Add()
        {
            PlayerEdit EditedPlayer = new PlayerEdit();
            EditedPlayer.teams = db.Teams.ToList();
            return View(EditedPlayer);
        }
        [HttpPost]
        public ActionResult Create(string PlayerFname_New, string PlayerLname_New,string PlayerAge_New, string PlayerNationality_New, string PlayerPosition_New, int TeamName_New)
        {
            string subquery = "insert into Players (PlayerFName, PlayerLName, PlayerAge,PlayerNationality, PlayerPosition, team_TeamID) " +
                           "values (@firstname,@lastname,@age,@nationality,@position,@teamname)";

            SqlParameter[] myparams = new SqlParameter[6];
            myparams[0] = new SqlParameter("@firstname", PlayerFname_New);
            myparams[1] = new SqlParameter("@lastname", PlayerLname_New);
            myparams[2] = new SqlParameter("@age", PlayerAge_New);
            myparams[3] = new SqlParameter("@nationality", PlayerNationality_New);
            myparams[4] = new SqlParameter("@position", PlayerPosition_New);
            myparams[5] = new SqlParameter("@teamname", TeamName_New);

            db.Database.ExecuteSqlCommand(subquery, myparams);
            Debug.WriteLine(subquery);

            return RedirectToAction("List"); // after adding a team, it will redirect back to List View.
        }

        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Player player = db.Players.Find(id);
            if (player == null)
            {
                return HttpNotFound();
            }
            return View(player);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {

            PlayerEdit EditedPlayer = new PlayerEdit();
            EditedPlayer.teams = db.Teams.ToList();

            EditedPlayer.player = db.Players.Find(id);

            return View(EditedPlayer);
        }

        [HttpPost]
        public ActionResult Edit(int? id, string PlayerFName_Edit, string PlayerLName_Edit,string PlayerAge_Edit,string PlayerNationality_Edit,string PlayerPosition_Edit, int TeamID_Edit)
        {
            if ((id == null) || (db.Teams.Find(id) == null))
            {
                return HttpNotFound();
            }
            string subquery = "UPDATE players SET PlayerFName = @playerFname, PlayerLName = @playerLname, " +
                              "PlayerAge= @playerage, PlayerNationality= @playernationality, PlayerPosition= @playerposition," +
                              " team_TeamID =@team " +
                              " WHERE playerid = @id";
            SqlParameter[] myparams = new SqlParameter[7];
            myparams[0] = new SqlParameter("@playerFname", PlayerFName_Edit);
            myparams[1] = new SqlParameter("@playerLname", PlayerLName_Edit);
            myparams[2] = new SqlParameter("@playerage", PlayerAge_Edit);
            myparams[3] = new SqlParameter("@playernationality", PlayerNationality_Edit);
            myparams[4] = new SqlParameter("@playerposition", PlayerPosition_Edit);
            myparams[5] = new SqlParameter("@team", TeamID_Edit);
            myparams[6] = new SqlParameter("@id", id);

            db.Database.ExecuteSqlCommand(subquery, myparams);

            return RedirectToAction("List");
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Player player = db.Players.Find(id);
            if (player == null)
            {
                return HttpNotFound();
            }

            return View(player);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Player player = db.Players.Find(id);
            db.Players.Remove(player);
            db.SaveChanges();
            return RedirectToAction("Index"); // To go back to Country/Index 

        }
    }
}

PassionProject_N01329942/Views/Player/Add.cshtml
@model PassionProject_N01329942.Models.ViewModels.PlayerEdit
@{
    ViewBag.Title = "Add";
}
<div class="title">
    <h2>Add a New Player</h2>
</div>


<form method="POST" action="/Player/Create" id="myform">
    <div class="row">
        <div class="label">
            <label>Player First Name: </label>
        </div>
        <div class="right-side">
            <input type="text" id="PlayerFname_New" name="PlayerFname_New" required="required" />
        </div>
    </div>
    <div class="row">
        <div class="label">
            <label>Player Last Name: </label>
        </div>
        <div class="right-side">
            <input type="text" id="PlayerLname_New" name="PlayerLname_New" required="required" />
        </div>
    </div>
    <div class="row">
        <div class="label">
            <label>Player Age: </label>
        </div>
        <div class="right-side">
            <input type="text" id="PlayerAge_New" name="PlayerAge_New" required="required" />
        </div>
    </div>
    <div class="row">
        <div class="label">
            <label>Player Nationality: </label>
        </div>
        <div class="right-side">
            <input type="text" id="PlayerNationality_New" name="PlayerNationality_New" required="required" />
        </div>
    </div>
    <div class="row">
        <div class="label">
            <label>Player Position: </label>
        </div>
        <div class="right-side">
            <input type="text" id="PlayerPosition_New" name="PlayerPosition_New" required="required" />
        </div>
    </div>
    <div class="row">
        <div class="label">
            <label>Team Name: </label>
        </div>
        <div class="right-side">
            <select id="TeamName_New" name="TeamName_New">
                @foreach (var team in Model.teams)
                {
                    <option value="@team.TeamID">@team.TeamName</option>
                }
            </select>
        </div>
    </div>
    <div class="row center">
        <input type="submit" value="ADD" id="submit" />
    </div>
</form>
<div class="center">
    <button class="buttonLink">@Html.ActionLink("Back to Teams list", "Index")</button>
</div>

PassionProject_N01329942/Views/Player/Delete.cshtml
@model PassionProject_N01329942.Models.Player
@{
    ViewBag.Title = "Delete";
}
<div class="title">
    <h2>Delete a Player</h2>

    <h2>Do you want to delete this player from the list ?</h2>

    <h4>@Html.DisplayFor(model => model.PlayerFName) @Html.DisplayFor(model => model.PlayerLName) </h4>

</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="center">
        <input type="submit" value="Delete" id="submit" />
    </div>
    <div class="center">
        <button class="buttonLink">@Html.ActionLink("Back to teams list", "List")</button>
    </div>
}

PassionProject_N01329942/Views/Player/Edit.cshtml
@model PassionProject_N01329942.Models.ViewModels.PlayerEdit
@{
    ViewBag.Title = "Edit";
}

<div class="title">
    <h2>Edit @Model.player.PlayerFName @Model.player.PlayerLName</h2>


    <form method="POST" action="@Model.player.PlayerID">
        <div class="row hidden">
            <div class="label">
                <label>Team Name:</label>
            </div>
            <div class="right-side">
                <input type="text" value="@Model.player.PlayerFName" id="PlayerFName_Edit" name="PlayerFName_Edit" />
            </div>
        </div>
        <div class="row">
            <div class="label">
                <label>Establish Date:</label>
            </div>
            <div class="right-side">
                <input type="text" value="@Model.player.PlayerLName" id="PlayerLName_Edit" name="PlayerLName_Edit" />
            </div>
        </div>
        <div class="row">
            <div class="label">
                <label>Establish Date:</label>
            </div>
            <div class="right-side">
                <input type="text" value="@Model.player.PlayerAge" id="PlayerAge_Edit" name="PlayerAge_Edit" />
            </div>
        </div>
        <div class="row">
            <div class="label">
                <label>Establish Date:</label>
            </div>
            <div class="right-side">
                <input type="text" value="@Model.player.PlayerNationality" id="PlayerNationality_Edit" name="PlayerNationality_Edit" />
            </div>
        </div>
        <div class="row">
            <div class="label">
                <label>Establish Date:</label>
            </div>
            <div class="right-side">
                <input type="text" value="@Model.player.PlayerPosition" id="PlayerPosition_Edit" name="PlayerPosition_Edit" />
            </div>
        </div>
        <div class="row">
            <div class="label">
                <label>Team Name:</label>
            </div>
            <div class="right-side">
                <select id="TeamID_Edit" name="TeamID_Edit">
                    @foreach (var team in Model.teams)
                    {
                        <option value="@team.TeamID"
                                @if (team.TeamID == Model.player.team.TeamID)
                                {
                                    var selected = "selected"; @selected ;
                                }>
                            @team.TeamName
                        </option>
                    }
                </select>
            </div>
        </div>
        <div class="row">
            <input type="submit" value="Save" id="submit" />
        </div>
    </form>

</div>
<div class="center">
    <button class="buttonLink">@Html.ActionLink("Back to Teams list", "List")</button>
</div>

PassionProject_N01329942/Views/Player/List.cshtml
@model IEnumerable<PassionProject_N01329942.Models.Player>
    <!-- We have used IEnumerable interface since we will have a 
        rendering loop to iterate through Player database to
        get the content of the database-->
@{
    ViewBag.Title = "List";
}
<div class="title">
    <h2>Players</h2>

    <button class="buttonLink">@Html.ActionLink("Add a new Player", "Add", "Player")</button>
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PlayerFName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PlayerLName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PlayerAge)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PlayerNationality)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PlayerPosition)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.team.TeamName)
        </th>
        <th>
            Features
        </th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.PlayerFName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PlayerLName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PlayerAge)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PlayerNationality)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PlayerPosition)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.team.TeamName)
        </td>
        <td>
            @Html.ActionLink("Details", "details", new { id = item.PlayerID }) |
            @Html.ActionLink("Edit", "Edit", new { id = item.PlayerID }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.PlayerID })
        </td>
    </tr>
    }
</table>

PassionProject_N01329942/Views/Player/details.cshtml
@model  PassionProject_N01329942.Models.Player
@{
    ViewBag.Title = "details";
}
<div class="title">
    <h2>Player details</h2>

    <h2><strong>@Model.PlayerFName @Model.PlayerLName</strong></h2>

    <h3>Age is <strong>@Model.PlayerAge</strong></h3>

    <h3>He is from <strong>@Model.PlayerNationality</strong></h3>

    <h3>His position is <strong>@Model.PlayerPosition</strong></h3>

    <h3>He plays for <strong>@Model.team.TeamName</strong></h3>

    <div>
        <button class="buttonLink">@Html.ActionLink("Back to team List", "Index")</button>
    </div>
</div>